server:
  port: 80
  session:
    timeout: 1800
  tomcat: 
    max-threads: 1000
    min-spare-threads: 200
    accept-count: 1000
    max-connections: 1000
 # connection-timeout: 60
 
spring:
   datasource: 
     name: master
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/earn_turn_db
     username: root
     password: liliu 
   redis:
     host: 127.0.0.1
     password: liliu
     port: 6379 
     database: 1
     timeout: 3000
     pool: 
       min-idle: 100
       max-idle: 300
       max-active: 800 
myPugin: 
  projectName: EarnTurn
  location: c://config/thirdParty.properties
  articleUrl: http://web1.nieyue.com/article.html
  shareUrl: http://192.168.7.111/share.html
  shareDomain: localhost
  gmwDomain: localhost
  ssDomain: localhost
  adDomain: localhost
  jsAd: console.log('dev')
  requestAuth: requestAuthDev
  rabbitmq:
    DIRECT_EXCHANGE: test.exchange.direct
    DIRECT_ROUTINGKEY: test.routingkey.direct
    DIRECT_QUEUE: test.queue.direct